[versions]
core-ktx = "1.10.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.08.00"

[libraries]
# Lottie for Android Compose
# http://airbnb.io/lottie/#/android-compose
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version = "6.1.0" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3", version = "1.1.1" }
koin = { group = "io.insert-koin", name = "koin-android", version = "3.4.3" }
data-store = { group = "androidx.datastore", name = "datastore-preferences", version = "1.0.0" }